UPSTREAM: soc/mediatek/common/include/soc: Include header file for check_member
To fix the build error below when include i2c_common.h, we should
include the necessary header for check_member.

"""
src/soc/mediatek/common/include/soc/i2c_common.h:24:42: error: expected ')' before numeric constant
   24 | check_member(mt_i2c_dma_regs, dma_tx_len, 0x24);
      |                                          ^~~~~
      |                                          )
"""

TEST=abuild -t google/geralt -b ciri -a

(cherry picked from commit 04b89c5a37f223d7a7a666ade1f970be5564c9ab)

Original-Signed-off-by: Ruihai Zhou <zhouruihai@huaqin.corp-partner.google.com>
Original-Change-Id: I266571686e452e2b7514afee42ff0a48f8891831
Original-Reviewed-on: https://review.coreboot.org/c/coreboot/+/81684
Original-Reviewed-by: Elyes Haouas <ehaouas@noos.fr>
Original-Reviewed-by: Yidi Lin <yidilin@google.com>
Original-Reviewed-by: Eric Lai <ericllai@google.com>
Original-Reviewed-by: cong yang <yangcong5@huaqin.corp-partner.google.com>
Original-Tested-by: build bot (Jenkins) <no-reply@coreboot.org>
GitOrigin-RevId: 04b89c5a37f223d7a7a666ade1f970be5564c9ab
Change-Id: I9c2c74d3d225a19ff91fe6eb5d104e64bbd9c0cf
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/coreboot/+/5438854
Reviewed-by: Rob Barnes <robbarnes@google.com>
Tested-by: ChromeOS Prod (Robot) <chromeos-ci-prod@chromeos-bot.iam.gserviceaccount.com>
Commit-Queue: Rob Barnes <robbarnes@google.com>