UPSTREAM: soc/mt/mt8196/gpio_eint.c: Add assert message
This fixes the following warning with clang (18.1.6):
src/soc/mediatek/mt8196/gpio_eint.c:259:44: error: '_Static_assert' with no message is a C23 extension [-Werror,-Wc23-extensions]
  259 | _Static_assert(ARRAY_SIZE(eint_data) == 293);
      |                                            ^
      |

(cherry picked from commit bc853b72aca27aba3431be9775373755ea9b6435)

(cherry picked from commit 1d91241809bbec9ae34135e9c5d0191f894f1a44)

Original-Original-Change-Id: I934b6d7ee8e8a0c204a4e328331c3ff3cd0f07de
Original-Original-Signed-off-by: Arthur Heymans <arthur@aheymans.xyz>
Original-Original-Reviewed-on: https://review.coreboot.org/c/coreboot/+/84618
Original-Original-Reviewed-by: Felix Held <felix-coreboot@felixheld.de>
Original-Original-Tested-by: build bot (Jenkins) <no-reply@coreboot.org>
Original-GitOrigin-RevId: bc853b72aca27aba3431be9775373755ea9b6435
Original-Cr-Build-Id: 8735131191759872513
Original-Cr-Build-Url: https://cr-buildbucket.appspot.com/build/8735131191759872513
Original-Copybot-Job-Name: coreboot-main-copybot-downstream
Change-Id: Iba1514a24ba17c93aa6aeeceec7d36a95624ede1
Original-Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/coreboot/+/5905694
Original-Reviewed-by: Kshitij Shah <tij@google.com>
Original-Tested-by: ChromeOS Prod (Robot) <chromeos-ci-prod@chromeos-bot.iam.gserviceaccount.com>
Original-Commit-Queue: Kshitij Shah <tij@google.com>
GitOrigin-RevId: 1d91241809bbec9ae34135e9c5d0191f894f1a44
Cr-Build-Id: 8735014747486419857
Cr-Build-Url: https://cr-buildbucket.appspot.com/build/8735014747486419857
Copybot-Job-Name: android-main-coreboot-copybot-downstream
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/coreboot/+/5907742
Reviewed-by: Jayvik Desai <jayvik@google.com>
Commit-Queue: Jayvik Desai <jayvik@google.com>
Tested-by: ChromeOS Prod (Robot) <chromeos-ci-prod@chromeos-bot.iam.gserviceaccount.com>