UPSTREAM: include/stdbool: Don't unconditionally typedef bool
When compiling with the C23 standard, bool, true, and false are
pre-defined by the language, so defining them in stdbool.h isn't allowed.
This fixes the following error:
src/include/stdbool.h:6:17: error: two or more data types in declaration specifiers
    6 | typedef _Bool   bool;
      |                 ^~~~
src/include/stdbool.h:6:1: error: useless type name in empty declaration [-Werror]
    6 | typedef _Bool   bool;
      | ^~~~~~~

(cherry picked from commit 37dcaf86039ef3b4f06a87fb0e4b210c83c73c53)

(cherry picked from commit faa0dfe91db133e8125fc5ae72902861f0817caf)

Original-Original-Change-Id: Iec9b4e3f308008ece773ce3460daff97370161ea
Original-Original-Signed-off-by: Elyes Haouas <ehaouas@noos.fr>
Original-Original-Reviewed-on: https://review.coreboot.org/c/coreboot/+/83909
Original-Original-Tested-by: build bot (Jenkins) <no-reply@coreboot.org>
Original-Original-Reviewed-by: Nico Huber <nico.h@gmx.de>
Original-GitOrigin-RevId: 37dcaf86039ef3b4f06a87fb0e4b210c83c73c53
Original-Cr-Build-Id: 8735857637506445297
Original-Cr-Build-Url: https://cr-buildbucket.appspot.com/build/8735857637506445297
Original-Copybot-Job-Name: coreboot-main-copybot-downstream
Change-Id: I7116b5535fc1df968a0fdb5cdab107df4982fb44
Original-Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/coreboot/+/5889910
Original-Reviewed-by: Maulik Vaghela <maulikvaghela@google.com>
Original-Reviewed-by: Subrata Banik <subratabanik@chromium.org>
Original-Tested-by: ChromeOS Prod (Robot) <chromeos-ci-prod@chromeos-bot.iam.gserviceaccount.com>
Original-Commit-Queue: Subrata Banik <subratabanik@chromium.org>
GitOrigin-RevId: faa0dfe91db133e8125fc5ae72902861f0817caf
Cr-Build-Id: 8735377135656758641
Cr-Build-Url: https://cr-buildbucket.appspot.com/build/8735377135656758641
Copybot-Job-Name: android-main-coreboot-copybot-downstream
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/coreboot/+/5890958
Reviewed-by: Grzegorz Bernacki <bernacki@google.com>
Reviewed-by: Yu-Ping Wu <yupingso@chromium.org>
Tested-by: ChromeOS Prod (Robot) <chromeos-ci-prod@chromeos-bot.iam.gserviceaccount.com>
Commit-Queue: Yu-Ping Wu <yupingso@chromium.org>