UPSTREAM: soc/nvidia: Put static keyword at the beginning of declarations
In order to comply with the more recent style of declarations, put the
static keyword at the beginning.

Fixes following GCC error when the related flag is set:

  error: 'static' is not at beginning of declaration [-Werror=old-style-declaration]

(cherry picked from commit d74ee60f71fd45449cd710a58a7f2ca9fae2ca49)

Original-Change-Id: Ida683319f7a0c428a9e4808821075abdd9fcb504
Original-Signed-off-by: Felix Singer <felixsinger@posteo.net>
Original-Reviewed-on: https://review.coreboot.org/c/coreboot/+/79856
Original-Reviewed-by: Julius Werner <jwerner@chromium.org>
Original-Tested-by: build bot (Jenkins) <no-reply@coreboot.org>
Original-Reviewed-by: Paul Menzel <paulepanter@mailbox.org>
GitOrigin-RevId: d74ee60f71fd45449cd710a58a7f2ca9fae2ca49
Change-Id: I9a2bfe9400b7d914187a03036e0d0b69b337d268
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/coreboot/+/5184264
Commit-Queue: Brett Brotherton <bbrotherton@google.com>
Tested-by: ChromeOS Prod (Robot) <chromeos-ci-prod@chromeos-bot.iam.gserviceaccount.com>
Reviewed-by: Brett Brotherton <bbrotherton@google.com>