UPSTREAM: soc/intel/alderlake: Fix uninitialized usb_cfg pointer Android Bringup: See http://go/android-fw-sync
This patch addresses uninitialized usb_cfg pointer warning which is also
an error - src/soc/intel/alderlake/fsp_params.c:936:48: error: 'usb_cfg'
may be used uninitialized in this function [-Werror=maybe-uninitialized]

BUG=None
TEST=./util/abuild/abuild

(cherry picked from commit 1d9bddf1632ccbb7ffd5d92c4608c3065df72c0f)

(cherry picked from commit c16559f531ef8eb6c19ea46e9d73cfdd072e4c1d)

Original-Original-Change-Id: I764fed561dfe2a571f3404fe505997edd7aa5ff7
Original-Original-Signed-off-by: Karthikeyan Ramasubramanian <kramasub@google.com>
Original-Original-Reviewed-on: https://review.coreboot.org/c/coreboot/+/84939
Original-Original-Reviewed-by: Jayvik Desai <jayvik@google.com>
Original-Original-Reviewed-by: Subrata Banik <subratabanik@google.com>
Original-Original-Tested-by: build bot (Jenkins) <no-reply@coreboot.org>
Original-GitOrigin-RevId: 1d9bddf1632ccbb7ffd5d92c4608c3065df72c0f
Original-Cr-Build-Id: 8731898458657424529
Original-Cr-Build-Url: https://cr-buildbucket.appspot.com/build/8731898458657424529
Original-Copybot-Job-Name: coreboot-main-copybot-downstream
Change-Id: I934e6f5ae2bf654211658553cba32e704341570f
Original-Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/coreboot/+/6003387
Original-Reviewed-by: Jonathon Murphy <jpmurphy@google.com>
Original-Commit-Queue: Jonathon Murphy <jpmurphy@google.com>
Original-Tested-by: ChromeOS Prod (Robot) <chromeos-ci-prod@chromeos-bot.iam.gserviceaccount.com>
GitOrigin-RevId: c16559f531ef8eb6c19ea46e9d73cfdd072e4c1d
Cr-Build-Id: 8731843854298481969
Cr-Build-Url: https://cr-buildbucket.appspot.com/build/8731843854298481969
Copybot-Job-Name: android-main-coreboot-copybot-downstream
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/coreboot/+/6003949
Tested-by: ChromeOS Prod (Robot) <chromeos-ci-prod@chromeos-bot.iam.gserviceaccount.com>
Reviewed-by: Jonathon Murphy <jpmurphy@google.com>
Commit-Queue: Jonathon Murphy <jpmurphy@google.com>