UPSTREAM: include/device: Add missing include
Fix the following error when including device/pciexp.h

src/include/device/pciexp.h: In function 'pciexp_is_downstream_port':
src/include/device/pciexp.h:42:24: error: 'PCI_EXP_TYPE_ROOT_PORT' undeclared (first use in this function)
   42 |         return type == PCI_EXP_TYPE_ROOT_PORT ||

by including pci_def.h.

(cherry picked from commit 440003d5d53ccb747f886f215b292b8362ef5bc1)

(cherry picked from commit 4d7b7b60b3c7e388a7b267ec53896c18ab8ff826)

Original-Original-Change-Id: Idfd36301a5e766bbe97c93afef88c97507a4c4dc
Original-Original-Signed-off-by: Patrick Rudolph <patrick.rudolph@9elements.com>
Original-Original-Reviewed-on: https://review.coreboot.org/c/coreboot/+/84791
Original-Original-Reviewed-by: Lean Sheng Tan <sheng.tan@9elements.com>
Original-Original-Reviewed-by: Shuo Liu <shuo.liu@intel.com>
Original-Original-Reviewed-by: Elyes Haouas <ehaouas@noos.fr>
Original-Original-Tested-by: build bot (Jenkins) <no-reply@coreboot.org>
Original-GitOrigin-RevId: 440003d5d53ccb747f886f215b292b8362ef5bc1
Original-Cr-Build-Id: 8733293405921231329
Original-Cr-Build-Url: https://cr-buildbucket.appspot.com/build/8733293405921231329
Original-Copybot-Job-Name: coreboot-main-copybot-downstream
Change-Id: Idf7408a21783b3439a42322b5c73c51c0e9d7625
Original-Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/coreboot/+/5952705
Original-Reviewed-by: Jakub Czapiga <czapiga@google.com>
Original-Tested-by: ChromeOS Prod (Robot) <chromeos-ci-prod@chromeos-bot.iam.gserviceaccount.com>
Original-Commit-Queue: Jakub Czapiga <czapiga@google.com>
GitOrigin-RevId: 4d7b7b60b3c7e388a7b267ec53896c18ab8ff826
Cr-Build-Id: 8733021614557178305
Cr-Build-Url: https://cr-buildbucket.appspot.com/build/8733021614557178305
Copybot-Job-Name: android-main-coreboot-copybot-downstream
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/coreboot/+/5961119
Reviewed-by: Jonathon Murphy <jpmurphy@google.com>
Tested-by: ChromeOS Prod (Robot) <chromeos-ci-prod@chromeos-bot.iam.gserviceaccount.com>
Reviewed-by: Yu-Ping Wu <yupingso@chromium.org>
Commit-Queue: Jonathon Murphy <jpmurphy@google.com>