UPSTREAM: soc/intel/pantherlake: Include FSP API header globally
As discussed under CB:88768, building for PantherLake targets fails due
to odd race-condition:
```
src/include/stdint.h:66:9: error: "INT32_MAX" redefined [-Werror]
   66 | #define INT32_MAX  ((int32_t)0x7FFFFFFF)
      |         ^~~~~~~~~
[...]
  129 |   #define INT32_MAX                       (0x7FFFFFFF)
      |           ^~~~~~~~~
```

Board maintainers shouldn't need to include the FSP API header in their
ports, adding this header globally to meminit.h resolves the
race-condition and allows the build to finish.

(cherry picked from commit 1e1e99d723c365d141201a9c396ba66bbbdcc208)

Original-cc1: all warnings being treated as errors
Original-make: *** Waiting for unfinished jobs....
Original-Change-Id: Id7656d476ca6db78ea74629ef37a20323362997a
Original-Signed-off-by: Alicja Michalska <alicja.michalska@9elements.com>
Original-Reviewed-on: https://review.coreboot.org/c/coreboot/+/91023
Original-Reviewed-by: Subrata Banik <subratabanik@google.com>
Original-Reviewed-by: Matt DeVillier <matt.devillier@gmail.com>
Original-Tested-by: build bot (Jenkins) <no-reply@coreboot.org>
Original-Reviewed-by: Jérémy Compostella <jeremy.compostella@intel.com>
GitOrigin-RevId: 1e1e99d723c365d141201a9c396ba66bbbdcc208
Cr-Build-Id: 8691109192213090081
Cr-Build-Url: https://cr-buildbucket.appspot.com/build/8691109192213090081
Copybot-Job-Name: coreboot-main-copybot-downstream
Change-Id: I61b9566be1346036dd037f77072b5e1daad8844c
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/coreboot/+/7531513
Commit-Queue: ChromeOS Copybot <copybot@chops-service-accounts.iam.gserviceaccount.com>
Bot-Commit: ChromeOS Copybot <copybot@chops-service-accounts.iam.gserviceaccount.com>
Tested-by: ChromeOS Copybot <copybot@chops-service-accounts.iam.gserviceaccount.com>