UPSTREAM: sb/intel/i82801gx/chip.h: Use 'bool' instead of 'int'
This to fix following error using Clang-16.0.0:
/cb-build/coreboot-toolchain.0/clang/APPLE_IMAC52/mainboard/apple/macbook21/static.c:66:19: error: implicit truncation from 'int' to a one-bit wide bit-field changes value from 1 to -1 [-Werror,-Wsingle-bit-bitfield-constant-conversion]
        .c4onc3_enable = 1,
                         ^
/cb-build/coreboot-toolchain.0/clang/APPLE_IMAC52/mainboard/apple/macbook21/static.c:75:32: error: implicit truncation from 'int' to a one-bit wide bit-field changes value from 1 to -1 [-Werror,-Wsingle-bit-bitfield-constant-conversion]
        .p_cnt_throttling_supported = 1,
                                      ^

(cherry picked from commit c46242f904b64daee36e6d478e1d88c623fb3c44)

Original-Change-Id: I691b51a97b359655c406bff28ee6562636d11015
Original-Signed-off-by: Elyes Haouas <ehaouas@noos.fr>
Original-Reviewed-on: https://review.coreboot.org/c/coreboot/+/73796
Original-Tested-by: build bot (Jenkins) <no-reply@coreboot.org>
Original-Reviewed-by: Felix Singer <felixsinger@posteo.net>
GitOrigin-RevId: c46242f904b64daee36e6d478e1d88c623fb3c44
Change-Id: Ia472aad2b6af4ad213b20fc944d3e8c21e49e43b
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/coreboot/+/4402163
Tested-by: CopyBot Service Account <copybot.service@gmail.com>
Reviewed-by: Kangheui Won <khwon@chromium.org>
Commit-Queue: Kangheui Won <khwon@chromium.org>