UPSTREAM: Revert "util/cbmem: Consolidate CBMEM and coreboot table access" Android Bringup: See http://go/android-fw-sync
This reverts commit c24a12db860f33cee2a8ff4c7fd66af3775fba5d.

Reason for revert: can't assume uint64_t or uintptr_t is a long. use proper printf modifiers instead.

```
cbmem.c:417:28: error: format specifies type 'unsigned long' but the argument
      has type 'uint64_t' (aka 'unsigned long long') [-Werror,-Wformat]
  417 |                 debug("Found at %#lx\n", address + i);
      |                                 ~~~~     ^~~~~~~~~~~
      |                                 %#llx
cbmem.c:50:40: note: expanded from macro 'debug'
   50 | #define debug(x...) if(verbose) printf(x)
      |                                        ^
cbmem.c:1321:21: error: format specifies type 'unsigned long' but the argument
      has type 'uintptr_t' (aka 'unsigned int') [-Werror,-Wformat]
 1321 |                         printf("%08lx:", start_address + i);
      |                                 ~~~~~    ^~~~~~~~~~~~~~~~~
      |                                 %08x
2 errors generated.
```

(cherry picked from commit 712dfb376136a9d69451624c59c0dd6b880a3597)

(cherry picked from commit 4a96b9847001d0db8fd02bbe943fc8492cd774dc)

Original-Original-make: *** [<builtin>: cbmem.o] Error 1
Original-Original-Signed-off-by: Jon Murphy <jpmurphy@google.com>
Original-Original-Change-Id: I6e074b0c6c8247f85cd69d64c0e8584c5826e35a
Original-Original-Reviewed-on: https://review.coreboot.org/c/coreboot/+/88016
Original-Original-Reviewed-by: Subrata Banik <subratabanik@google.com>
Original-Original-Reviewed-by: Matt DeVillier <matt.devillier@gmail.com>
Original-Original-Reviewed-by: Stefan Reinauer <stefan.reinauer@coreboot.org>
Original-Original-Reviewed-by: Jakub "Kuba" Czapiga <czapiga@google.com>
Original-Original-Tested-by: build bot (Jenkins) <no-reply@coreboot.org>
Original-GitOrigin-RevId: 712dfb376136a9d69451624c59c0dd6b880a3597
Original-Cr-Build-Id: 8712509981906017889
Original-Cr-Build-Url: https://cr-buildbucket.appspot.com/build/8712509981906017889
Original-Copybot-Job-Name: coreboot-main-copybot-downstream
Change-Id: If6f6c0c596a758bc1f91a6c11d7329336ecd9160
Original-Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/coreboot/+/6629667
Original-Reviewed-by: Jon Murphy <jpmurphy@google.com>
Original-Tested-by: ChromeOS Copybot <copybot@chops-service-accounts.iam.gserviceaccount.com>
GitOrigin-RevId: 4a96b9847001d0db8fd02bbe943fc8492cd774dc
Cr-Build-Id: 8712486300225947489
Cr-Build-Url: https://cr-buildbucket.appspot.com/build/8712486300225947489
Copybot-Job-Name: android-main-coreboot-copybot-downstream
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/coreboot/+/6631592
Commit-Queue: ChromeOS Copybot <copybot@chops-service-accounts.iam.gserviceaccount.com>
Tested-by: ChromeOS Copybot <copybot@chops-service-accounts.iam.gserviceaccount.com>
Bot-Commit: ChromeOS Copybot <copybot@chops-service-accounts.iam.gserviceaccount.com>