UPSTREAM: doc/releases/4.22: Remove transitions from sections
Sections may not start with transitions. Remove them.

This fixes the following Sphinx error:

  ERROR: Document or section may not begin with a transition.

(cherry picked from commit facdfe46229931cab242bf975894e100ff95c80f)

Original-Change-Id: I519af83df14e44b0709dee7e338dba1ee6413f0a
Original-Signed-off-by: Felix Singer <felixsinger@posteo.net>
Original-Reviewed-on: https://review.coreboot.org/c/coreboot/+/77440
Original-Reviewed-by: Nicholas Chin <nic.c3.14@gmail.com>
Original-Tested-by: build bot (Jenkins) <no-reply@coreboot.org>
GitOrigin-RevId: facdfe46229931cab242bf975894e100ff95c80f
Change-Id: Ie88bf8a3bc26aa1a8f76b92df5618ff7691ead40
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/coreboot/+/4816766
Tested-by: ChromeOS Prod (Robot) <chromeos-ci-prod@chromeos-bot.iam.gserviceaccount.com>
Reviewed-by: Shelley Chen <shchen@chromium.org>
Commit-Queue: Shelley Chen <shchen@chromium.org>