UPSTREAM: soc/qualcomm/sc7280/socinfo: Add missing <console/console.h> Android Bringup: See http://go/android-fw-sync
This to fix Wimplicit-function-declaration error:
src/soc/qualcomm/sc7280/socinfo.c:67:2: error: call to undeclared function 'die'; ISO C99 and later do not support implicit function declarations [-Wimplicit-function-declaration]
   67 |         die("could not match jtagid\n");
      |         ^
src/soc/qualcomm/sc7280/socinfo.c:81:2: error: call to undeclared function 'die'; ISO C99 and later do not support implicit function declarations [-Wimplicit-function-declaration]
   81 |         die("could not match jtagid\n");
      |         ^

(cherry picked from commit 1e0ce7a9d8d67e83c67e22dd51d5b8e8f6e7cb8d)

(cherry picked from commit 8e087bdb8af0f6efbca9d691637858c894909f15)

Original-Original-Change-Id: If930e39d0c7231975c1a11179fa7dbd9fcc0d1d1
Original-Original-Signed-off-by: Elyes Haouas <ehaouas@noos.fr>
Original-Original-Reviewed-on: https://review.coreboot.org/c/coreboot/+/85166
Original-Original-Reviewed-by: Felix Singer <service+coreboot-gerrit@felixsinger.de>
Original-Original-Tested-by: build bot (Jenkins) <no-reply@coreboot.org>
Original-GitOrigin-RevId: 1e0ce7a9d8d67e83c67e22dd51d5b8e8f6e7cb8d
Original-Cr-Build-Id: 8730870591242854033
Original-Cr-Build-Url: https://cr-buildbucket.appspot.com/build/8730870591242854033
Original-Copybot-Job-Name: coreboot-main-copybot-downstream
Change-Id: Ic25dcb6bbc93eb251ffbac8051429651654683d5
Original-Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/coreboot/+/6034556
Original-Tested-by: Kangheui Won <khwon@chromium.org>
Original-Commit-Queue: Kangheui Won <khwon@chromium.org>
Original-Reviewed-by: Kangheui Won <khwon@chromium.org>
Original-Tested-by: ChromeOS Prod (Robot) <chromeos-ci-prod@chromeos-bot.iam.gserviceaccount.com>
GitOrigin-RevId: 8e087bdb8af0f6efbca9d691637858c894909f15
Cr-Build-Id: 8730847287754551601
Cr-Build-Url: https://cr-buildbucket.appspot.com/build/8730847287754551601
Copybot-Job-Name: android-main-coreboot-copybot-downstream
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/coreboot/+/6033166
Tested-by: ChromeOS Prod (Robot) <chromeos-ci-prod@chromeos-bot.iam.gserviceaccount.com>
Commit-Queue: Jonathon Murphy <jpmurphy@google.com>
Reviewed-by: Jonathon Murphy <jpmurphy@google.com>