UPSTREAM: amdfwtool: make fields unsigned
The value stored in `gen` is only ever `1` or `0`. Storing `1` causes
Clang to warn, since the only valid values for a 1-bit int are -1 and 0:
```
amdfwtool.c:1487:27: error: implicit truncation from 'int' to a one-bit
wide bit-field changes value from 1 to -1
[-Werror,-Wsingle-bit-bitfield-constant-conversion]
 1487 |                 amd_romsig->efs_gen.gen = EFS_BEFORE_SECOND_GEN;
```

TEST=Rebuilt coreboot; no warning was emitted.

(cherry picked from commit 794934cbeebb586847c98cc3d7ea04fa09a7330b)

(cherry picked from commit 7041cb393d26e973e12959e900f1805cf9f3a695)

Original-Original-Change-Id: Ibd83be8302e8a717db7e7dc86a403b5648976586
Original-Original-Signed-off-by: George Burgess IV <gbiv@google.com>
Original-Original-Reviewed-on: https://review.coreboot.org/c/coreboot/+/83412
Original-Original-Reviewed-by: Felix Held <felix-coreboot@felixheld.de>
Original-Original-Reviewed-by: Matt DeVillier <matt.devillier@gmail.com>
Original-Original-Tested-by: build bot (Jenkins) <no-reply@coreboot.org>
Original-Original-Reviewed-by: Raul Rangel <rrangel@chromium.org>
Original-GitOrigin-RevId: 794934cbeebb586847c98cc3d7ea04fa09a7330b
Change-Id: I7da699ad6cc1662648cce230690f1d16c5672c8d
Original-Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/coreboot/+/5704460
Original-Tested-by: ChromeOS Prod (Robot) <chromeos-ci-prod@chromeos-bot.iam.gserviceaccount.com>
Original-Reviewed-by: Shelley Chen <shchen@chromium.org>
Original-Commit-Queue: Shelley Chen <shchen@chromium.org>
GitOrigin-RevId: 7041cb393d26e973e12959e900f1805cf9f3a695
Cr-Build-Id: 8740088177278986785
Cr-Build-Url: https://cr-buildbucket.appspot.com/build/8740088177278986785
Copybot-Job-Name: android-main-coreboot-copybot-downstream
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/coreboot/+/5764096
Commit-Queue: Subrata Banik <subratabanik@chromium.org>
Tested-by: ChromeOS Prod (Robot) <chromeos-ci-prod@chromeos-bot.iam.gserviceaccount.com>
Reviewed-by: Subrata Banik <subratabanik@chromium.org>