UPSTREAM: arch/arm64: Avoid GCC warning about out of bounds array access
With the update to GCC 13 a new warning about subtracting numbers from
arrays appears.

src/arch/arm64/armv8/mmu.c:296:9: error: array subscript -1 is outside array bounds of 'u8[]' {aka 'unsigned char[]'} [-Werror=array-bounds=]

(cherry picked from commit 9ba7bada0890671654f534715c134d0259ca55c3)

Original-Change-Id: I4757ca2e7ad3f969d7416041ea40c3e9866cdf49
Original-Signed-off-by: Zebreus <lennarteichhorn@googlemail.com>
Original-Reviewed-on: https://review.coreboot.org/c/coreboot/+/79014
Original-Reviewed-by: Felix Singer <service+coreboot-gerrit@felixsinger.de>
Original-Tested-by: build bot (Jenkins) <no-reply@coreboot.org>
GitOrigin-RevId: 9ba7bada0890671654f534715c134d0259ca55c3
Change-Id: I2af2b021b984d017b040f18662e9957a43e76dfd
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/coreboot/+/5042259
Tested-by: ChromeOS Prod (Robot) <chromeos-ci-prod@chromeos-bot.iam.gserviceaccount.com>
Commit-Queue: Jonathon Murphy <jpmurphy@google.com>
Reviewed-by: Jonathon Murphy <jpmurphy@google.com>