UPSTREAM: soc/mediatek/common/pcie: Add DEVTREE_CONST qualifier
Currently pcie.c is built into ramstage only, where DEVTREE_CONST is an
empty macro, so there's no problem with that. However, if we would like
to include that file in pre-ramstage, then DEVTREE_CONST would be
'const', leading to the following build error:

```
src/soc/mediatek/common/pcie.c:104:26: error: assignment discards
'const' qualifier from pointer target type [-Werror=discarded-qualifiers]
104 |                 root_dev = pcidev_path_on_root(devfn);
    |                          ^
```

BUG=none
TEST=emerge-cherry coreboot

(cherry picked from commit d86c5bf83b66565c437b0c3f399c61305c33d870)

(cherry picked from commit 8083d12603253561f04b81489d5e66d0caf99c87)

Original-Original-Change-Id: Ia7c95424019ec0dca50bbc6be7f81b6180d06d6e
Original-Original-Signed-off-by: Yidi Lin <yidilin@chromium.org>
Original-Original-Reviewed-on: https://review.coreboot.org/c/coreboot/+/84113
Original-Original-Reviewed-by: Jianjun Wang <jianjun.wang@mediatek.com>
Original-Original-Tested-by: build bot (Jenkins) <no-reply@coreboot.org>
Original-Original-Reviewed-by: Yu-Ping Wu <yupingso@google.com>
Original-GitOrigin-RevId: d86c5bf83b66565c437b0c3f399c61305c33d870
Original-Cr-Build-Id: 8737823253745763217
Original-Cr-Build-Url: https://cr-buildbucket.appspot.com/build/8737823253745763217
Original-Copybot-Job-Name: coreboot-main-copybot-downstream
Change-Id: I360f3b8e4ea17a517cdcad5ddc2c2070305c3335
Original-Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/coreboot/+/5832281
Original-Commit-Queue: Kangheui Won <khwon@chromium.org>
Original-Tested-by: Rob Barnes <robbarnes@google.com>
Original-Reviewed-by: Kangheui Won <khwon@chromium.org>
Original-Reviewed-by: Yidi Lin <yidilin@google.com>
Original-Reviewed-by: Rob Barnes <robbarnes@google.com>
GitOrigin-RevId: 8083d12603253561f04b81489d5e66d0caf99c87
Cr-Build-Id: 8737642060337374529
Cr-Build-Url: https://cr-buildbucket.appspot.com/build/8737642060337374529
Copybot-Job-Name: android-main-coreboot-copybot-downstream
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/coreboot/+/5836289
Commit-Queue: Yu-Ping Wu <yupingso@chromium.org>
Tested-by: ChromeOS Prod (Robot) <chromeos-ci-prod@chromeos-bot.iam.gserviceaccount.com>
Reviewed-by: Yu-Ping Wu <yupingso@chromium.org>