UPSTREAM: sb/intel/ibexpeak/Makefile.mk: Add shared ramstage ../bd82x6x/cfr.c
Recent addition of a shared Intel ME CFR setup menu for bd82x6x did not
take into account that ibexpeak ME also relies on that code. There for
currently building the Lenovo ThinkPad X201 with CFR menu fails with:

"undefined reference to `sb_cfr_set_string'"

See commit 6f581f48084a ("sb/intel/bd82x6x: Add CFR menu for Intel ME")

By including '../bd82x6x/cfr.c' in ramstage guarded by a CFR option it
is possible to build a working CFR menu based Lenovo ThinkPad X201 port
although testing on real hardware shows that the ME CFR setup options
are not effective yet. Fixing that still needs to be investigated.

(cherry picked from commit 713b7ca4444aa1b9b3f2efed0f387da4a4f0c7cb)

Original-Change-Id: I33643fcb10b6d1d8406ef2d8ea072194e43df265
Original-Signed-off-by: Walter Sonius <walterav1984@gmail.com>
Original-Reviewed-on: https://review.coreboot.org/c/coreboot/+/95383
Original-Reviewed-by: Patrick Rudolph <patrick.rudolph@9elements.com>
Original-Tested-by: build bot (Jenkins) <no-reply@coreboot.org>
GitOrigin-RevId: 713b7ca4444aa1b9b3f2efed0f387da4a4f0c7cb
Cr-Build-Id: 8670815471986730849
Cr-Build-Url: https://cr-buildbucket.appspot.com/build/8670815471986730849
Copybot-Job-Name: coreboot-main-copybot-downstream
Change-Id: I876c3498c07e6f1b0380d288eaf0dd8b4f70c803
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/coreboot/+/8402039
Bot-Commit: copybot@chops-service-accounts.iam.gserviceaccount.com <copybot@chops-service-accounts.iam.gserviceaccount.com>
Tested-by: copybot@chops-service-accounts.iam.gserviceaccount.com <copybot@chops-service-accounts.iam.gserviceaccount.com>
Commit-Queue: copybot@chops-service-accounts.iam.gserviceaccount.com <copybot@chops-service-accounts.iam.gserviceaccount.com>