UPSTREAM: mb/ocp/tiogapass: Fix build failure Android Bringup: See http://go/android-fw-sync
Add console.c to SMM stage as well. Fixes the build failure:
"undefined reference to `get_uart_baudrate'" when CONFIG_DEBUG_SMI
is set.

(cherry picked from commit 50905e7cdc9f0030cdeec6ab0eb70128bacc15e0)

(cherry picked from commit 5ef9303c3329661e9a10ec65df5927423bc348cb)

Original-Original-Change-Id: I2587287b0074a56c49b7434553c69cae97aaa1b4
Original-Original-Signed-off-by: Patrick Rudolph <patrick.rudolph@9elements.com>
Original-Original-Reviewed-on: https://review.coreboot.org/c/coreboot/+/85135
Original-Original-Tested-by: build bot (Jenkins) <no-reply@coreboot.org>
Original-Original-Reviewed-by: Alicja Michalska <ahplka19@gmail.com>
Original-Original-Reviewed-by: Lean Sheng Tan <sheng.tan@9elements.com>
Original-GitOrigin-RevId: 50905e7cdc9f0030cdeec6ab0eb70128bacc15e0
Original-Cr-Build-Id: 8731028479029462145
Original-Cr-Build-Url: https://cr-buildbucket.appspot.com/build/8731028479029462145
Original-Copybot-Job-Name: coreboot-main-copybot-downstream
Change-Id: Ib83c5d04fd04aceed3401b96e380fe4c0f5003f1
Original-Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/coreboot/+/6028911
Original-Tested-by: ChromeOS Prod (Robot) <chromeos-ci-prod@chromeos-bot.iam.gserviceaccount.com>
Original-Reviewed-by: Kangheui Won <khwon@chromium.org>
Original-Commit-Queue: Kangheui Won <khwon@chromium.org>
GitOrigin-RevId: 5ef9303c3329661e9a10ec65df5927423bc348cb
Cr-Build-Id: 8730937883673029553
Cr-Build-Url: https://cr-buildbucket.appspot.com/build/8730937883673029553
Copybot-Job-Name: android-main-coreboot-copybot-downstream
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/coreboot/+/6030327
Reviewed-by: Yu-Ping Wu <yupingso@chromium.org>
Tested-by: ChromeOS Prod (Robot) <chromeos-ci-prod@chromeos-bot.iam.gserviceaccount.com>
Commit-Queue: Jonathon Murphy <jpmurphy@google.com>
Reviewed-by: Jonathon Murphy <jpmurphy@google.com>