UPSTREAM: Makefile.mk: Suppress stack-usage LTO link warning Android Bringup: See http://go/android-fw-sync
Suppress the following warning during linking with gcc:
src/drivers/spi/spi_flash.c: In function 'spi_flash_cmd_write':
src/drivers/spi/spi_flash.c:138:5: error: stack usage might be unbounded [-Werror=stack-usage=]
  138 | int spi_flash_cmd_write(const struct spi_slave *spi, const u8 *cmd,

(cherry picked from commit 01dfc9b18730189445353422a5569e9d9865f5e3)

(cherry picked from commit 83d90500016cd945895f5113bbbd4daf5772b050)

Original-Original-Change-Id: If08d6d543a4fcff07003af8d1f8dd59ab79f42f8
Original-Original-Signed-off-by: Arthur Heymans <arthur@aheymans.xyz>
Original-Original-Reviewed-on: https://review.coreboot.org/c/coreboot/+/84044
Original-Original-Tested-by: build bot (Jenkins) <no-reply@coreboot.org>
Original-Original-Reviewed-by: Angel Pons <th3fanbus@gmail.com>
Original-GitOrigin-RevId: 01dfc9b18730189445353422a5569e9d9865f5e3
Original-Cr-Build-Id: 8732025048093146161
Original-Cr-Build-Url: https://cr-buildbucket.appspot.com/build/8732025048093146161
Original-Copybot-Job-Name: coreboot-main-copybot-downstream
Change-Id: I5b8e1e967c020742ab492f79ca1403021eca9c3e
Original-Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/coreboot/+/5997327
Original-Tested-by: ChromeOS Prod (Robot) <chromeos-ci-prod@chromeos-bot.iam.gserviceaccount.com>
Original-Reviewed-by: Nick Vaccaro <nvaccaro@google.com>
Original-Commit-Queue: Nick Vaccaro <nvaccaro@google.com>
GitOrigin-RevId: 83d90500016cd945895f5113bbbd4daf5772b050
Cr-Build-Id: 8731843854298481969
Cr-Build-Url: https://cr-buildbucket.appspot.com/build/8731843854298481969
Copybot-Job-Name: android-main-coreboot-copybot-downstream
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/coreboot/+/6001787
Reviewed-by: Jonathon Murphy <jpmurphy@google.com>
Tested-by: ChromeOS Prod (Robot) <chromeos-ci-prod@chromeos-bot.iam.gserviceaccount.com>
Commit-Queue: Jonathon Murphy <jpmurphy@google.com>