Use $VBOOT_SOURCE instead of hard-coded 3rdparty/vboot path
When building with build-board.sh we get an error
"romstage.c:48:10: fatal error: 2struct.h: No such file or directory"
because firmware/2lib/include is missing from CC includes.
It works with emerge because it copies vboot to 3rdparty/vboot.

TEST: build with build-board.sh
Change-Id: I65a94ed54612c77f12690b4ffd75c020f096228c
Signed-off-by: Nikolai Vyssotski <nikolai.vyssotski@amd.corp-partner.google.com>
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/coreboot/+/2219132
Reviewed-by: Raul E Rangel <rrangel@chromium.org>
Reviewed-by: Simon Glass <sjg@chromium.org>
Commit-Queue: Raul E Rangel <rrangel@chromium.org>