UPSTREAM: treewide: Apply nonstring attribute to unterminated strings
Applying the attribute silences the following error and allows
compilation with GCC 15.2.

  error: initializer-string for array of 'char' truncates NUL terminator but destination lacks 'nonstring' attribute

(cherry picked from commit e57478e23804c7414ec3027b1b2b0e65c8da7bb5)

Original-Change-Id: I33cf3219f34e297de03f67d3e73058b10930c9f8
Original-Signed-off-by: Felix Singer <felixsinger@posteo.net>
Original-Reviewed-on: https://review.coreboot.org/c/coreboot/+/90631
Original-Tested-by: build bot (Jenkins) <no-reply@coreboot.org>
Original-Reviewed-by: Maximilian Brune <maximilian.brune@9elements.com>
GitOrigin-RevId: e57478e23804c7414ec3027b1b2b0e65c8da7bb5
Cr-Build-Id: 8686149002080806929
Cr-Build-Url: https://cr-buildbucket.appspot.com/build/8686149002080806929
Copybot-Job-Name: coreboot-main-copybot-downstream
Change-Id: I00f5eb84c1f314339ead1af800de8edbf2b41620
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/coreboot/+/7708940
Tested-by: Jon Murphy <jpmurphy@google.com>
Reviewed-by: Jeremy Bettis <jbettis@chromium.org>
Commit-Queue: Jon Murphy <jpmurphy@google.com>
Reviewed-by: Keith Short <keithshort@chromium.org>