CHROMIUM: drivers/usb/acpi: Fix build
Build 12672.353.0 introduces a bug that breaks the build:

src/drivers/usb/acpi/usb_acpi.c:95:25: error:  Kstruct acpi_gpio has no member named active_low

Fix the build by changing the parameter name to the original value.

BUG=b:175717266
BRANCH=firmware-hatch-12672.B
TEST=cros tryjob -g 2592500 firmware-hatch-12672.B-firmwarebranch-tryjob

Fixes: f1d98bc74 (UPSTREAM: drivers/usb/acpi: Add support for privacy_gpio)
Signed-off-by: Ricardo Ribalda <ribalda@chromium.org>
Change-Id: Ib600668dd9d8a0fb2853175cb01fc22e5586c212
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/coreboot/+/2592500
Reviewed-by: Furquan Shaikh <furquan@chromium.org>
Reviewed-by: Shelley Chen <shchen@chromium.org>