UPSTREAM: vc/intel/edk2-stable202111: Resolve compilation error in EDK2 202111
Remove those MSVC compiler defaults checks so that the GCC defaults for
wchar_t can be used with UDK_202111_BINDING Kconfig.

Compilation error:
src/vendorcode/intel/edk2/edk2-stable202111/MdePkg/Include/Base.h:807:25:
Specification Data Type requirements"
src/vendorcode/intel/edk2/edk2-stable202111/MdePkg/Include/Base.h:807:25:
Specification Data Type requirements"

BUG=b:296433836
TEST=Able to build google/crassk with UDK_202111_BINDING.

(cherry picked from commit 760b572e0dabcf014da7ae7a059c9e508369eb84)

Original-error: static assertion failed: "sizeof (L\'A\') does not meet UEFI
Original-error: static assertion failed: "sizeof (L\"A\") does not meet UEFI
Original-Change-Id: Ib2716436a910b43a5e546afdedb9eec88c5da8c6
Original-Signed-off-by: Ronak Kanabar <ronak.kanabar@intel.com>
Original-Reviewed-on: https://review.coreboot.org/c/coreboot/+/81328
Original-Reviewed-by: Subrata Banik <subratabanik@google.com>
Original-Reviewed-by: Arthur Heymans <arthur@aheymans.xyz>
Original-Reviewed-by: Krishna P Bhat D <krishna.p.bhat.d@intel.com>
Original-Tested-by: build bot (Jenkins) <no-reply@coreboot.org>
GitOrigin-RevId: 760b572e0dabcf014da7ae7a059c9e508369eb84
Change-Id: I6cb6cb29fea5ce723923b72419e2a4f2ca0b798c
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/coreboot/+/5389559
Reviewed-by: Reka Norman <rekanorman@chromium.org>
Commit-Queue: Reka Norman <rekanorman@chromium.org>
Tested-by: ChromeOS Prod (Robot) <chromeos-ci-prod@chromeos-bot.iam.gserviceaccount.com>