UPSTREAM: sb/amd/pi/hudson: fix gpio.h and smi.h include location
This fixes the following compile error when trying to build the APU2
board with HAVE_SMI_HANDLER selected and the NO_SMM select removed:

In file included from src/soc/amd/common/block/gpio/gpio.c:8:
src/include/gpio.h:6:10: fatal error: soc/gpio.h: No such file or directory
    6 | #include <soc/gpio.h> /* IWYU pragma: export */
      |          ^~~~~~~~~~~~

(cherry picked from commit 2768e36f07edf4574d264b74febe9fe803153c17)

Original-Signed-off-by: Felix Held <felix-coreboot@felixheld.de>
Original-Change-Id: Ie06044b12f5cbcc55a2706ec566afd2eb294c62b
Original-Reviewed-on: https://review.coreboot.org/c/coreboot/+/79846
Original-Reviewed-by: Matt DeVillier <matt.devillier@amd.corp-partner.google.com>
Original-Tested-by: build bot (Jenkins) <no-reply@coreboot.org>
GitOrigin-RevId: 2768e36f07edf4574d264b74febe9fe803153c17
Change-Id: I22fbca77d596911a8dfb92c3b4cd60138d78b8cf
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/coreboot/+/5188352
Commit-Queue: Subrata Banik <subratabanik@chromium.org>
Tested-by: Subrata Banik <subratabanik@chromium.org>
Reviewed-by: Subrata Banik <subratabanik@chromium.org>