UPSTREAM: mb/google/kahlee/var/careena: Make sure bid isn't used uninitialized
GCC with LTO cought this.

Warning:
src/mainboard/google/kahlee/variants/careena/variant.c:44:12: error: 'bid' may be used uninitialized [-Werror=maybe-uninitialized]
   44 |         if (bid == 7)
      |            ^
src/mainboard/google/kahlee/variants/careena/variant.c: In function 'car_stage_entry':
src/mainboard/google/kahlee/variants/careena/variant.c:24:18: note: 'bid' was declared here
   24 |         uint32_t bid;

(cherry picked from commit 4a334bc9a1ba9b38b048bebc7fefe77af5017151)

(cherry picked from commit 526fbe51ffab0f723b5d4adff101524b613665c2)

Original-Original-Change-Id: Ie732b5be5cd9dc0abaf1a5efe023bcb0738dba1d
Original-Original-Signed-off-by: Arthur Heymans <arthur@aheymans.xyz>
Original-Original-Reviewed-on: https://review.coreboot.org/c/coreboot/+/84206
Original-Original-Reviewed-by: Marshall Dawson <marshalldawson3rd@gmail.com>
Original-Original-Reviewed-by: coreboot org <coreboot.org@gmail.com>
Original-Original-Tested-by: build bot (Jenkins) <no-reply@coreboot.org>
Original-GitOrigin-RevId: 4a334bc9a1ba9b38b048bebc7fefe77af5017151
Original-Cr-Build-Id: 8735286459267190753
Original-Cr-Build-Url: https://cr-buildbucket.appspot.com/build/8735286459267190753
Original-Copybot-Job-Name: coreboot-main-copybot-downstream
Change-Id: I9a65f700ba9a6aaa1d48d5d05092f295098e8c3d
Original-Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/coreboot/+/5901692
Original-Reviewed-by: Kshitij Shah <tij@google.com>
Original-Commit-Queue: Kshitij Shah <tij@google.com>
Original-Tested-by: ChromeOS Prod (Robot) <chromeos-ci-prod@chromeos-bot.iam.gserviceaccount.com>
GitOrigin-RevId: 526fbe51ffab0f723b5d4adff101524b613665c2
Cr-Build-Id: 8735014747486419857
Cr-Build-Url: https://cr-buildbucket.appspot.com/build/8735014747486419857
Copybot-Job-Name: android-main-coreboot-copybot-downstream
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/coreboot/+/5904606
Tested-by: ChromeOS Prod (Robot) <chromeos-ci-prod@chromeos-bot.iam.gserviceaccount.com>
Commit-Queue: Jayvik Desai <jayvik@google.com>
Reviewed-by: Jayvik Desai <jayvik@google.com>