UPSTREAM: drivers/option/cfr.c: Replace memcpy() to avoid uninitialized object
When updating clang to version 21.1.5, we now get the following error
when compiling the CFR code.
```
src/drivers/option/cfr.c:287:19: error: default initialization of an
      object of type 'struct sm_object' with const member leaves the object uninitialized
      [-Werror,-Wdefault-const-init-field-unsafe]
  287 |         struct sm_object sm_obj_copy;
```

In this specific case its actually not an issue, but initialize the
variable from the start to avoid the error and arguably make the code
easier to read.

(cherry picked from commit 91594f4894f041947b4cfdf0e76b5a9aeb3ac382)

Original-Signed-off-by: Maximilian Brune <maximilian.brune@9elements.com>
Original-Change-Id: Ib0b22e20a7482ab29d997a3e3c3bec4a1db1a4f1
Original-Reviewed-on: https://review.coreboot.org/c/coreboot/+/89958
Original-Reviewed-by: Elyes Haouas <ehaouas@noos.fr>
Original-Reviewed-by: Paul Menzel <paulepanter@mailbox.org>
Original-Tested-by: build bot (Jenkins) <no-reply@coreboot.org>
GitOrigin-RevId: 91594f4894f041947b4cfdf0e76b5a9aeb3ac382
Cr-Build-Id: 8698017211679441185
Cr-Build-Url: https://cr-buildbucket.appspot.com/build/8698017211679441185
Copybot-Job-Name: coreboot-main-copybot-downstream
Change-Id: I2113c00b89b0f34082f447b38564e60f32099413
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/coreboot/+/7157834
Bot-Commit: ChromeOS Copybot <copybot@chops-service-accounts.iam.gserviceaccount.com>
Tested-by: ChromeOS Copybot <copybot@chops-service-accounts.iam.gserviceaccount.com>
Commit-Queue: ChromeOS Copybot <copybot@chops-service-accounts.iam.gserviceaccount.com>